// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the MyFirstModule module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Test1Builder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_Test1");
		return builder;
	}

	public static void aCT_Test1(IContext context)
	{
		aCT_Test1Builder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Test2Builder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_Test2");
		return builder;
	}

	public static void aCT_Test2(IContext context)
	{
		aCT_Test2Builder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Test3Builder(
		myfirstmodule.proxies.MyFile _myFile
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_Test3");
		builder = builder.withParam("MyFile", _myFile);
		return builder;
	}

	public static void aCT_Test3(
		IContext context,
		myfirstmodule.proxies.MyFile _myFile
	)
	{
		aCT_Test3Builder(
				_myFile
			)
			.execute(context);
	}
}
