// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package localfileoperations.actions;

import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import org.apache.commons.io.IOUtils;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Writes the contents of a FileDocument to a location on the local server.
 */
public class FileDocumentToFile extends CustomJavaAction<java.lang.Void>
{
	private java.lang.String file;
	private IMendixObject __fileDocument;
	private system.proxies.FileDocument fileDocument;

	public FileDocumentToFile(IContext context, java.lang.String file, IMendixObject fileDocument)
	{
		super(context);
		this.file = file;
		this.__fileDocument = fileDocument;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.fileDocument = this.__fileDocument == null ? null : system.proxies.FileDocument.initialize(getContext(), __fileDocument);

		// BEGIN USER CODE
		File newFile = new File(file);
		InputStream is = Core.getFileDocumentContent(getContext(), __fileDocument);
		OutputStream os = new FileOutputStream(newFile);
		try {
			IOUtils.copy(is, os);
		} finally {
			try { is.close(); } catch (Exception e) {}
			try { os.close(); } catch (Exception e) {}
		}
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "FileDocumentToFile";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
