// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package localfileoperations.actions;

import java.io.File;
import java.io.FileInputStream;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Reads the contents of a file and stores it in a FileDocument.
 */
public class FileToFileDocument extends UserAction<java.lang.Void>
{
	private final java.lang.String file;
	/** @deprecated use result.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __result;
	private final system.proxies.FileDocument result;

	public FileToFileDocument(
		IContext context,
		java.lang.String _file,
		IMendixObject _result
	)
	{
		super(context);
		this.file = _file;
		this.__result = _result;
		this.result = _result == null ? null : system.proxies.FileDocument.initialize(getContext(), _result);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		File f = new File(file);
		Core.storeFileDocumentContent(getContext(), __result, new FileInputStream(f));
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "FileToFileDocument";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
