// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package localfileoperations.actions;

import java.io.File;
import org.apache.commons.io.FileUtils;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class MoveFile extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String source;
	private java.lang.String dest;

	public MoveFile(IContext context, java.lang.String source, java.lang.String dest)
	{
		super(context);
		this.source = source;
		this.dest = dest;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		FileUtils.moveFile(new File(source), new File(dest));
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "MoveFile";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
