// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package localfileoperations.actions;

import java.io.File;
import org.apache.commons.io.FileUtils;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.UserAction;

public class MoveDirectory extends UserAction<java.lang.Void>
{
	private final java.lang.String source;
	private final java.lang.String dest;
	private final java.lang.Boolean createDestDir;

	public MoveDirectory(
		IContext context,
		java.lang.String _source,
		java.lang.String _dest,
		java.lang.Boolean _createDestDir
	)
	{
		super(context);
		this.source = _source;
		this.dest = _dest;
		this.createDestDir = _createDestDir;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		FileUtils.moveDirectory(new File(source), new File(dest));
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "MoveDirectory";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
