// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package localfileoperations.proxies;

public class File implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject fileMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "LocalFileOperations.File";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FullNamePath("FullNamePath"),
		Name("Name"),
		Path("Path"),
		Size("Size"),
		IsFile("IsFile"),
		IsDirectory("IsDirectory"),
		IsHidden("IsHidden"),
		IsSymlink("IsSymlink"),
		LastModified("LastModified"),
		Executable("Executable"),
		Readable("Readable"),
		Writeable("Writeable");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public File(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected File(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject fileMendixObject)
	{
		if (fileMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, fileMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.fileMendixObject = fileMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static localfileoperations.proxies.File initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new localfileoperations.proxies.File(context, mendixObject);
	}

	public static localfileoperations.proxies.File load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return localfileoperations.proxies.File.initialize(context, mendixObject);
	}

	/**
	 * @return value of FullNamePath
	 */
	public final java.lang.String getFullNamePath()
	{
		return getFullNamePath(getContext());
	}

	/**
	 * @param context
	 * @return value of FullNamePath
	 */
	public final java.lang.String getFullNamePath(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FullNamePath.toString());
	}

	/**
	 * Set value of FullNamePath
	 * @param fullnamepath
	 */
	public final void setFullNamePath(java.lang.String fullnamepath)
	{
		setFullNamePath(getContext(), fullnamepath);
	}

	/**
	 * Set value of FullNamePath
	 * @param context
	 * @param fullnamepath
	 */
	public final void setFullNamePath(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fullnamepath)
	{
		getMendixObject().setValue(context, MemberNames.FullNamePath.toString(), fullnamepath);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Path
	 */
	public final java.lang.String getPath()
	{
		return getPath(getContext());
	}

	/**
	 * @param context
	 * @return value of Path
	 */
	public final java.lang.String getPath(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Path.toString());
	}

	/**
	 * Set value of Path
	 * @param path
	 */
	public final void setPath(java.lang.String path)
	{
		setPath(getContext(), path);
	}

	/**
	 * Set value of Path
	 * @param context
	 * @param path
	 */
	public final void setPath(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String path)
	{
		getMendixObject().setValue(context, MemberNames.Path.toString(), path);
	}

	/**
	 * @return value of Size
	 */
	public final java.lang.Long getSize()
	{
		return getSize(getContext());
	}

	/**
	 * @param context
	 * @return value of Size
	 */
	public final java.lang.Long getSize(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Size.toString());
	}

	/**
	 * Set value of Size
	 * @param size
	 */
	public final void setSize(java.lang.Long size)
	{
		setSize(getContext(), size);
	}

	/**
	 * Set value of Size
	 * @param context
	 * @param size
	 */
	public final void setSize(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long size)
	{
		getMendixObject().setValue(context, MemberNames.Size.toString(), size);
	}

	/**
	 * @return value of IsFile
	 */
	public final java.lang.Boolean getIsFile()
	{
		return getIsFile(getContext());
	}

	/**
	 * @param context
	 * @return value of IsFile
	 */
	public final java.lang.Boolean getIsFile(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsFile.toString());
	}

	/**
	 * Set value of IsFile
	 * @param isfile
	 */
	public final void setIsFile(java.lang.Boolean isfile)
	{
		setIsFile(getContext(), isfile);
	}

	/**
	 * Set value of IsFile
	 * @param context
	 * @param isfile
	 */
	public final void setIsFile(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isfile)
	{
		getMendixObject().setValue(context, MemberNames.IsFile.toString(), isfile);
	}

	/**
	 * @return value of IsDirectory
	 */
	public final java.lang.Boolean getIsDirectory()
	{
		return getIsDirectory(getContext());
	}

	/**
	 * @param context
	 * @return value of IsDirectory
	 */
	public final java.lang.Boolean getIsDirectory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsDirectory.toString());
	}

	/**
	 * Set value of IsDirectory
	 * @param isdirectory
	 */
	public final void setIsDirectory(java.lang.Boolean isdirectory)
	{
		setIsDirectory(getContext(), isdirectory);
	}

	/**
	 * Set value of IsDirectory
	 * @param context
	 * @param isdirectory
	 */
	public final void setIsDirectory(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isdirectory)
	{
		getMendixObject().setValue(context, MemberNames.IsDirectory.toString(), isdirectory);
	}

	/**
	 * @return value of IsHidden
	 */
	public final java.lang.Boolean getIsHidden()
	{
		return getIsHidden(getContext());
	}

	/**
	 * @param context
	 * @return value of IsHidden
	 */
	public final java.lang.Boolean getIsHidden(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsHidden.toString());
	}

	/**
	 * Set value of IsHidden
	 * @param ishidden
	 */
	public final void setIsHidden(java.lang.Boolean ishidden)
	{
		setIsHidden(getContext(), ishidden);
	}

	/**
	 * Set value of IsHidden
	 * @param context
	 * @param ishidden
	 */
	public final void setIsHidden(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean ishidden)
	{
		getMendixObject().setValue(context, MemberNames.IsHidden.toString(), ishidden);
	}

	/**
	 * @return value of IsSymlink
	 */
	public final java.lang.Boolean getIsSymlink()
	{
		return getIsSymlink(getContext());
	}

	/**
	 * @param context
	 * @return value of IsSymlink
	 */
	public final java.lang.Boolean getIsSymlink(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsSymlink.toString());
	}

	/**
	 * Set value of IsSymlink
	 * @param issymlink
	 */
	public final void setIsSymlink(java.lang.Boolean issymlink)
	{
		setIsSymlink(getContext(), issymlink);
	}

	/**
	 * Set value of IsSymlink
	 * @param context
	 * @param issymlink
	 */
	public final void setIsSymlink(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean issymlink)
	{
		getMendixObject().setValue(context, MemberNames.IsSymlink.toString(), issymlink);
	}

	/**
	 * @return value of LastModified
	 */
	public final java.util.Date getLastModified()
	{
		return getLastModified(getContext());
	}

	/**
	 * @param context
	 * @return value of LastModified
	 */
	public final java.util.Date getLastModified(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.LastModified.toString());
	}

	/**
	 * Set value of LastModified
	 * @param lastmodified
	 */
	public final void setLastModified(java.util.Date lastmodified)
	{
		setLastModified(getContext(), lastmodified);
	}

	/**
	 * Set value of LastModified
	 * @param context
	 * @param lastmodified
	 */
	public final void setLastModified(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date lastmodified)
	{
		getMendixObject().setValue(context, MemberNames.LastModified.toString(), lastmodified);
	}

	/**
	 * @return value of Executable
	 */
	public final java.lang.Boolean getExecutable()
	{
		return getExecutable(getContext());
	}

	/**
	 * @param context
	 * @return value of Executable
	 */
	public final java.lang.Boolean getExecutable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Executable.toString());
	}

	/**
	 * Set value of Executable
	 * @param executable
	 */
	public final void setExecutable(java.lang.Boolean executable)
	{
		setExecutable(getContext(), executable);
	}

	/**
	 * Set value of Executable
	 * @param context
	 * @param executable
	 */
	public final void setExecutable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean executable)
	{
		getMendixObject().setValue(context, MemberNames.Executable.toString(), executable);
	}

	/**
	 * @return value of Readable
	 */
	public final java.lang.Boolean getReadable()
	{
		return getReadable(getContext());
	}

	/**
	 * @param context
	 * @return value of Readable
	 */
	public final java.lang.Boolean getReadable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Readable.toString());
	}

	/**
	 * Set value of Readable
	 * @param readable
	 */
	public final void setReadable(java.lang.Boolean readable)
	{
		setReadable(getContext(), readable);
	}

	/**
	 * Set value of Readable
	 * @param context
	 * @param readable
	 */
	public final void setReadable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean readable)
	{
		getMendixObject().setValue(context, MemberNames.Readable.toString(), readable);
	}

	/**
	 * @return value of Writeable
	 */
	public final java.lang.Boolean getWriteable()
	{
		return getWriteable(getContext());
	}

	/**
	 * @param context
	 * @return value of Writeable
	 */
	public final java.lang.Boolean getWriteable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Writeable.toString());
	}

	/**
	 * Set value of Writeable
	 * @param writeable
	 */
	public final void setWriteable(java.lang.Boolean writeable)
	{
		setWriteable(getContext(), writeable);
	}

	/**
	 * Set value of Writeable
	 * @param context
	 * @param writeable
	 */
	public final void setWriteable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean writeable)
	{
		getMendixObject().setValue(context, MemberNames.Writeable.toString(), writeable);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return fileMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final localfileoperations.proxies.File that = (localfileoperations.proxies.File) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
