// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package localfileoperations.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the LocalFileOperations module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_DeleteBuilder(
		localfileoperations.proxies.File _file
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("LocalFileOperations.ACT_Delete");
		builder = builder.withParam("File", _file);
		return builder;
	}

	public static void aCT_Delete(
		IContext context,
		localfileoperations.proxies.File _file
	)
	{
		aCT_DeleteBuilder(
				_file
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_OpenBuilder(
		localfileoperations.proxies.File _file,
		localfileoperations.proxies.Explorer _explorer
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("LocalFileOperations.ACT_Open");
		builder = builder.withParam("File", _file);
		builder = builder.withParam("Explorer", _explorer);
		return builder;
	}

	public static void aCT_Open(
		IContext context,
		localfileoperations.proxies.File _file,
		localfileoperations.proxies.Explorer _explorer
	)
	{
		aCT_OpenBuilder(
				_file,
				_explorer
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_ParentBuilder(
		localfileoperations.proxies.Explorer _explorer
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("LocalFileOperations.ACT_Parent");
		builder = builder.withParam("Explorer", _explorer);
		return builder;
	}

	public static void aCT_Parent(
		IContext context,
		localfileoperations.proxies.Explorer _explorer
	)
	{
		aCT_ParentBuilder(
				_explorer
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_ReadFileBuilder(
		localfileoperations.proxies.File _file
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("LocalFileOperations.ACT_ReadFile");
		builder = builder.withParam("File", _file);
		return builder;
	}

	public static void aCT_ReadFile(
		IContext context,
		localfileoperations.proxies.File _file
	)
	{
		aCT_ReadFileBuilder(
				_file
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_GetExplorerBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("LocalFileOperations.DS_GetExplorer");
		return builder;
	}

	public static localfileoperations.proxies.Explorer dS_GetExplorer(IContext context)
	{
		Object result = dS_GetExplorerBuilder().execute(context);
		return result == null ? null : localfileoperations.proxies.Explorer.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_ListFilesBuilder(
		localfileoperations.proxies.Explorer _explorer
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("LocalFileOperations.DS_ListFiles");
		builder = builder.withParam("Explorer", _explorer);
		return builder;
	}

	public static java.util.List<localfileoperations.proxies.File> dS_ListFiles(
		IContext context,
		localfileoperations.proxies.Explorer _explorer
	)
	{
		Object result = dS_ListFilesBuilder(
				_explorer
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> localfileoperations.proxies.File.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder oCh_CurrentPathBuilder(
		localfileoperations.proxies.Explorer _explorer
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("LocalFileOperations.OCh_CurrentPath");
		builder = builder.withParam("Explorer", _explorer);
		return builder;
	}

	public static void oCh_CurrentPath(
		IContext context,
		localfileoperations.proxies.Explorer _explorer
	)
	{
		oCh_CurrentPathBuilder(
				_explorer
			)
			.execute(context);
	}
}
